import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import GainsightWrapper from "./components/GainsightWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="w-100 h-screen flex justify-center items-center">
          <GainsightWrapper scriptContent="" isHelmet={false}>
            {children}
          </GainsightWrapper>
          {/* <Script id="abc">{`console.log('script direct');`}</Script> */}
        </div>
      </body>
    </html>
  );
}
